version: '2'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  o12stack-test-center:
    image: observabilitystack/o12stack-test-center:5
    ports:
      - 8080:8080
    environment:
      SENTRY_DSN: ""

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards/o12stack-test-center.json:/var/lib/grafana/dashboards/o12stack-test-center.json
      