{
 "title": "o12stack Test center",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Jobs total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jobs_submitted_total", "legendFormat": "Jobs Submitted" },
    { "expr": "jobs_completed_total", "legendFormat": "Jobs Completed" }
   ]
  },
  {
   "title": "Job Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jobs_waiting", "legendFormat": "waiting / queued" }
   ]
  },
  {
   "title": "Job Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "job_wait_timer_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "job_duration_timer_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "PROC CPU" },
    { "expr": "system_cpu_usage", "legendFormat": "SYS CPU" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"o12stc\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}